const letterContainer = document.querySelector("#letter-container")
const optionsContainer = document.querySelector("#options-container")
const userInputSection = document.querySelector("#user-input-section")
const newGameContainer =document.querySelector("#new-game-container")
const resultText =document.querySelector("#result-text")
const newGameBtn =document.querySelector("#new-game-button")
const winMusic =document.querySelector("#winMusic")
const loseMusic =document.querySelector("#loseMusic")